In [2]:
import random
import numpy as np
from random import randint
from datetime import datetime
import time

In [19]:
# Вводиться число n. Вивести масив разміра nхn, в якому по
# діагоналі йдуть числа від 1 до n, а інші числа рівні 0
def task_1():
    n = int(input())
    start_time = datetime.now()
    matrix = []
    for number in range (1,n+1):
        array = []
        for number1 in range (1,n+1):
            if number1!=number:
                array.append(0)
            else:
                array.append(number1)
            if number1==n:
                matrix.append(array)
    print(datetime.now() - start_time)
    return matrix
    
task_1()    

1
0:00:00


[[1]]

In [20]:
def task_1_np():
    n = int(input())
    start_time = datetime.now()
    a = np.zeros((n, n), int)
    test = np.arange(1,n+1)
    print(test)
    np.fill_diagonal(a, test)
    print(datetime.now() - start_time)
    return a;

task_1_np()

1
[1]
0:00:00


array([[1]])

In [7]:
# Вводяться 4 числа n, m, r, c. Вивести масив розміру n на m, в
# якому в кожному r -му рядку і в кожному c-му стовпчику стоять 0, а інші
# елементи дорівнюють 1.
def task_3():
    n = int(input())
    m = int(input())
    r = int(input())
    c = int(input())
    matrix = []
    for i in range (0,n):
        array = []
        for j in range (0, m):
            if (i%r==0):
                array.append(0)
            else:
                if (j%c==0):
                    array.append(0)
                else:
                    array.append(1)
        matrix.append(array)
    return(matrix)
        
task_3()

6
7
2
3


[[0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 0, 1, 1, 0],
 [0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 0, 1, 1, 0],
 [0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 0, 1, 1, 0]]

In [13]:
def task_3_np():
    n = int(input())
    m = int(input())
    r = int(input())
    c = int(input())
    a = np.ones((n, m), int)
    a[::r ] = 0
    a[0:n,::c] = 0
    return a;

task_3_np()

6
7
2
3


array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 1, 1, 0]])

In [2]:
# Вводяться числа n і m. Вивести масив розміру n на m, в якому упершому рядку (рядок з нулевим індексом)
# йдуть числа від 0 до m-1, а всі інші елементи матриці дорівнюють 0.
def task_4(): 
    n,m=map(int,input().split())
    count = 0 
    text = "["
    for i in range(n):
        text= text+"["
        for j in range(n):
            if i==0 and count < m:
                text = text + str(count)
                count = count+1
            else:
                text = text + "0"
        text= text+"]"
        if i != n-1:
            text = text + "\n "
    text = text + "]"
    print(text)
    return text

task_4()

3 4
[[012]
 [000]
 [000]]


'[[012]\n [000]\n [000]]'

In [2]:
def task_4np():
    n,m=map(int,input().split())
    Z = np.zeros((n,n), dtype=int)
    P = np.arange(m)
    if m < n:
        Z[0, 0:m] = P[0:m] 
    if m >= n:
        Z[0, 0:n] = P[0:n]
    return Z

task_4np()

3 4


array([[0, 1, 2],
       [0, 0, 0],
       [0, 0, 0]])

In [3]:
# З клавіатури вводиться масив. Замінити всі ненульові елементи на -1.
def task_6():
    my_list = [int(el) for el in input().split()]
    for i, n in enumerate(my_list):
        if n != 0:
            my_list[i] = -1
    print(my_list)
    return my_list

task_6()

1 0 0 -10 1
[-1, 0, 0, -1, -1]


[-1, 0, 0, -1, -1]

In [6]:
def task_6_np():
    my_list = [int(el) for el in input().split()]
    my_array = np.array(my_list)
    my_array[my_array != 0] = -1
    return my_array

task_6_np()

1 0 0 -10 1


array([-1,  0,  0, -1, -1])

In [19]:
# Вводиться числа n i m. Створити масив випадкових значень n на m
# і обчислити мінімальне, максимальне значення, середнє та середньо
# квадратичне відхилення, округлене до 3 знаків після коми
def task_10():
    n = int(input())
    m = int(input())
    arr = []
    for i in range(n):
        arr.append([random.random()] * m)
    max_elem = arr[0][0]
    min_elem = arr[0][0]
    Sum = 0
    arr_length = n * m
    for i in range(len(arr)):
        for j in range(len(arr[i] )):
             Sum += arr[j][j]
             if arr[i][j] > max_elem:
                   max_elem =  arr[i][j]
             if arr[i][j] < min_elem:
                   min_elem =  arr[i][j]
    avg = Sum/arr_length
    Sum_dev_arr = 0
    for i in range(len(arr)):
        for j in range(len(arr[i] )):
            Sum_dev_arr += (arr[i][j] - avg)**2
    disperse = (Sum_dev_arr / arr_length)**0.5
    print("мінімум: ",min_elem)
    print("максімум: ",max_elem)
    print("середнє: ",avg)
    print("дисперсія", disperse)
    
task_10()

2
2
мінімум:  0.163331872094852
максімум:  0.7435306787742307
середнє:  0.4534312754345414
дисперсія 0.29009940333968937


In [24]:
def task_10_np():
    n = int(input())
    m = int(input())
    values = np.random.randint(10, size=(n,m))
    print(values)
    print("мінімум: ", np.min(values))
    print("максімум: ", np.max(values))
    print("середнє: ",np.average(values))
    print("дисперсія", np.std(values))

task_10_np()

3
4
[[4 6 8 0]
 [8 5 7 3]
 [4 5 5 6]]
мінімум:  0
максімум:  8
середнє:  5.083333333333333
дисперсія 2.1392496088322392


In [22]:
#Створити масив одиниць розміром n х n та створити в ньому «рамку», сформовану з 0.
def task_12(): 
    n = int(input()) 
    text = "["
    for i in range(n):
        text= text+"["
        for j in range(n):
            if i==0 or j==0 or i==n-1 or j==n-1:
                text = text + "0"
            else:
                text = text + "1"
        text= text+"]"
        if i != n-1:
            text = text + "\n "
    text = text + "]"
    print(text)
    return text

task_12()

5
[[00000]
 [01110]
 [01110]
 [01110]
 [00000]]


'[[00000]\n [01110]\n [01110]\n [01110]\n [00000]]'

In [18]:
def task_12_np():
    n = int(input())
    Z = np.zeros((n,n), dtype=int)
    Z[1:-1,1:-1] = 1
    return Z

task_12_np()

4


array([[0, 0, 0, 0],
       [0, 1, 1, 0],
       [0, 1, 1, 0],
       [0, 0, 0, 0]])

In [23]:
# Заповнити парні стовбчики матриці розміром n х n одиницями, а непарні – нулями.
def task_15(): 
    n = int(input())  
    text = "["
    for i in range(n):
        text= text+"["
        for j in range(n):
            if j%2:
                text = text + "1"
            else:
                text = text + "0"
        text= text+"]"
        if i != n-1:
            text = text + "\n "
    text = text + "]"
    print(text)
    return text

task_15()

4
[[0101]
 [0101]
 [0101]
 [0101]]


'[[0101]\n [0101]\n [0101]\n [0101]]'

In [20]:
def task_15_np():
    n = int(input())
    Z = np.ones((n,n), dtype=int)
    Z[::1,::2] = 0
    return Z

task_15_np()

3


array([[0, 1, 0],
       [0, 1, 0],
       [0, 1, 0]])

In [24]:
def task_17():
    n = int(input())
    vector = []
    for number in range(n+1):
        vector.append(number)
    for i in vector:
        if (i < n/2): 
             vector[i] = -vector[i]
        if (i > 3*n/4): 
             vector[i] = -vector[i]
    return vector

task_17()

12


[0, -1, -2, -3, -4, -5, 6, 7, 8, 9, -10, -11, -12]

In [34]:
def task_17_np():
    n = int(input())
    arr = np.arange(n+1)
    arr2= np.where((arr < n/2) | (arr>3*n/4), -arr, arr)
    print(arr2)
    
task_17_np()

12
[  0  -1  -2  -3  -4  -5   6   7   8   9 -10 -11 -12]


In [25]:
def task_18():
    n = int(input())
    randnums = [randint(0,99) for _ in range(n)]
    uniqRandNums = []

    for item in randnums: 
        if item not in uniqRandNums: 
            uniqRandNums.append(item)
    print("В послідовності ", randnums, "-", len(uniqRandNums), "унікальних чисел")
    
task_18()

6
В послідовності  [65, 44, 73, 24, 3, 63] - 6 унікальних чисел


In [40]:
def task_18_np():
    n = int(input())
    randnums= np.random.randint(0,99,n)
    print(len(np.unique(randnums)))
    print("В послідовності ",randnums, "-", len(np.unique(randnums)), "унікальних чисел")
    
task_18_np()

12
10
В послідовності  [77  9 57 70 34  5 30 79 59  9 25 34] -10 унікальних чисел


In [4]:
def transposeMatrix(m):
    return map(list,zip(*m))

def getMatrixMinor(m,i,j):
    return [row[:j] + row[j+1:] for row in (m[:i]+m[i+1:])]

def getMatrixDeterminant(m):
    if len(m) == 2:
        return m[0][0]*m[1][1]-m[0][1]*m[1][0]

    determinant = 0
    for c in range(len(m)):
        determinant += ((-1)**c)*m[0][c]*getMatrixDeterminant(getMatrixMinor(m,0,c))
    return determinant

def mult_matr(a,b):
    c=[[0 for i in range(3)] for i in range(3)]
    for i in range(3):
        for j in range(3):
            c[i][j] = sum(a[i][kk] * b[kk][j] for kk in range(3))
    return(c)

def getMatrixInverse(m):
    determinant = getMatrixDeterminant(m)
    #special case for 2x2 matrix:
    if len(m) == 2:
        return [[m[1][1]/determinant, -1*m[0][1]/determinant],
                [-1*m[1][0]/determinant, m[0][0]/determinant]]

    #find matrix of cofactors
    cofactors = []
    for r in range(len(m)):
        cofactorRow = []
        for c in range(len(m)):
            minor = getMatrixMinor(m,r,c)
            cofactorRow.append(((-1)**(r+c)) * getMatrixDeternminant(minor))
        cofactors.append(cofactorRow)
    cofactors = transposeMatrix(cofactors)
    for r in range(len(cofactors)):
        for c in range(len(cofactors)):
            cofactors[r][c] = cofactors[r][c]/determinant
    return cofactors

In [5]:
#вирішення рівняння без numpy
M =[[1,5,3,-4],[3,1,-2,0],[5,-7,0,10],[0,3,-5,0]]
M1 =[[20,5,3,-4],[9,1,-2,0],[-9,-7,0,10],[1,3,-5,0]]
M2 =[[1,20,3,-4],[3,9,-2,0],[5,-9,0,10],[0,1,-5,0]]
M3 =[[1,5,20,-4],[3,1,9,0],[5,-7,-9,10],[0,3,1,0]]
M4 =[[1,5,3,20],[3,1,-2,9],[5,-7,0,-9],[0,3,-5,1]]
start_time = datetime.now()
x1 = getMatrixDeterminant(M1)/getMatrixDeterminant(M)
x2 = getMatrixDeterminant(M2)/getMatrixDeterminant(M)
x3 = getMatrixDeterminant(M3)/getMatrixDeterminant(M)
x4 = getMatrixDeterminant(M4)/getMatrixDeterminant(M)
wNumpyR = datetime.now() - start_time
print(x1, x2, x3, x4)

3.0 2.0 1.0 -1.0


In [6]:
#вирішення рівняння з numpy
Md =np.array([[1,5,3,-4],[3,1,-2,0],[5,-7,0,10],[0,3,-5,0]])
Md2=np.array([20,9,-9,1])
start_time = datetime.now()
R = np.linalg.solve(Md,Md2)
numpyR = datetime.now() - start_time
print(R)

[ 3.  2.  1. -1.]


In [17]:
print(wNumpyR,numpyR)

0:00:00 0:00:00.018971


In [21]:
#матричне множення
p = [[3],[2],[1],[-1]]
def multMatrParams(a,b,k,m, n):
    c = [[None for i in range(k)] for i in range(m)]    # c: m × k

    for i in range(m):
        for j in range(k):       
            c[i][j] = sum(a[i][kk] * b[kk][j] for kk in range(n))
    return c
  
print(multMatrParams(Md, p, 1,4,4))

[[20], [9], [-9], [1]]


In [11]:
def sum_matr(a,b):
    c=[[0 for i in range(3)] for i in range(3)]
    for i in range(3):
        for j in range(3):
            c[i][j] = a[i][j]+b[i][j]
    return(c)
    
def dist_matr(a,b):
    c=[[0 for i in range(3)] for i in range(3)]
    for i in range(3):
        for j in range(3):
            c[i][j] = a[i][j]-b[i][j]
    return(c)
    
def mult_matr(a,b):
    c=[[0 for i in range(3)] for i in range(3)]
    for i in range(3):
        for j in range(3):
            c[i][j] = sum(a[i][kk] * b[kk][j] for kk in range(3))
    return(c)

def sq_matr(a):
    c=[[0 for i in range(3)] for i in range(3)]
    for i in range(3):
        for j in range(3):
            c[i][j] = sum(a[i][kk] * a[kk][j] for kk in range(3))
    return(c)

In [12]:
#обчислити значення матричного виразу без numpy
a=[[5,2,0],[10,4, 1],[7,3,2]]
b=[[3,6,-1],[-1,-2,0],[2,1,3]]
start_time = datetime.now()
C1=sum_matr(a,b)
A2=sq_matr(a)
B2=sq_matr(b)
C2=dist_matr(A2,B2)
R1=mult_matr(C2,C1)

print(R1)
print(datetime.now() - start_time)

[[541, 410, 9], [1198, 886, -32], [715, 582, -49]]
0:00:00.000999


In [13]:
#обчислити значення матричного виразу з numpy
a=[[5,2,0],[10,4, 1],[7,3,2]]
b=[[3,6,-1],[-1,-2,0],[2,1,3]]
   
start_time = datetime.now()
C = np.add(a,b)
A2 = np.dot(a,a)
B2 = np.dot(b,b)
D = np.subtract(A2,B2)
R2 = np.dot(D,C)

print(R2)
print(datetime.now() - start_time)

[[ 541  410    9]
 [1198  886  -32]
 [ 715  582  -49]]
0:00:00.000998


In [14]:
np.allclose(R1,R2)

True